sonar.projectKey=vinayakgyenagimath_github-actions-solar-system
sonar.organization=vinayakgyenagimath
 
sonar.sources=.
 
sonar.exclusions=node_modules/**,coverage/**
 
sonar.javascript.lcov.reportPaths=coverage/lcov.info
